### ISSUE TITLE
What's the difference between `nbsrc` and `nbrmd` and why did you split them up? 

### ISSUE THREAD

**Issue by grst** [mwouts/nbsrc#3]

**Comment by mwouts** [comment]
Thanks @grst for asking. That's a good question !

Basically I wanted to write two different documentations:
- one for saving notebooks as R markdown
- one for saving notebooks as source files.

The point in writing two documentations was 
- to write shorter and more focused documentations
- not to impress python only users with a mention of a R markdown, which they're not aware of, and which I am afraid would be of limited use to them (at least currently - this may change in the future, for instance if PyCharm extends [support for Rmd](https://youtrack.jetbrains.com/issue/PY-30090), or if reticulates comes to support [rich output](https://github.com/rstudio/reticulate/issues/281))

Most of the functionality is provided by `nbrmd` which was developed first, and actually there's no need to install `nbsrc`, unless people want the notebook <-> source command line converter.

I'll try at least to make that clear in the documentation. 

Also, if you have recommendations on how to best communicate on the two different features, please let me know!

**Comment by mwouts** [comment]
Both documentations were updated in v0.4.3. I close this issue for now, but advices remain welcome. Thanks Gregor for asking.
